experiment_name: FruitsFreshness
model_name: fruits-freshness-classifier
data_dir: data_splits
train_dir: data_splits/train
val_dir: data_splits/val
test_dir: data_splits/test
img_size: 224
batch_size: 32
epochs: 10
lr: 0.0005
metric_threshold:
  accuracy: 0.85
  f1_weighted: 0.85
classes:
  - fresh_apple
  - stale_apple
  - fresh_banana
  - stale_banana
  - fresh_bitter_gourd
  - stale_bitter_gourd
  - fresh_capsicum
  - stale_capsicum
  - fresh_orange 
  - stale_orange 
  - fresh_tomato
  - stale_tomato
tracking_uri: ./mlruns
