name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pyyaml
      - name: Lint
        run: |
          flake8 mlops_pipeline/scripts --max-line-length=120
      - name: Unit tests
        run: |
          pytest -q
